# Generated by Django 6.0.1 on 2026-01-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('stud_name', models.CharField(max_length=100)),
                ('per', models.FloatField()),
                ('photo', models.FileField(upload_to='images')),
            ],
        ),
    ]
