# Generated by Django 6.0.1 on 2026-01-19 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
    ]
